version: "{build}"

os: Windows Server 2016

environment:
  GOPATH: c:\gopath
  matrix:
    - MSI_ARCH: amd64
      GOARCH: amd64
    - MSI_ARCH: 386
      GOARCH: 386

clone_folder: c:\gopath\src\github.com\tony-harverson-moonpig\iislog-prometheus-exporter

install:
  - go version
  - set PATH=%GOPATH%\bin;c:\go\bin;%GOPATH%\bin\windows_%GOARCH%;%PATH%
  - go get -u github.com/prometheus/promu
  - choco install gitversion.portable -y

build_script:
  - ps: gitversion /output json /showvariable FullSemVer | Set-Content VERSION -PassThru
  - ps: build.ps1

artifacts:
  - name: Package
    path: 'bin/*.exe'
    path: 'bin/*.hcl'
