version: "{build}"

os: Visual Studio 2017

environment:
  GOPATH: c:\gopath
  matrix:
    - MSI_ARCH: 386
      GOARCH: 386

clone_folder: c:\gopath\src\github.com\tony-harverson-moonpig\iislog-prometheus-exporter

install:
  - go version
  - set PATH=%GOPATH%\bin;c:\go\bin;%GOPATH%\bin\windows_%GOARCH%;%PATH%
#  - go get -u github.com/prometheus/promu
#  - choco install gitversion.portable -y
#  - echo "hi there" > c:\gopath\src\github.com\tony-harverson-moonpig\iislog-prometheus-exporter\VERSION
#
build_script:
#  - ps: gitversion /output json /showvariable FullSemVer | Set-Content -force VERSION -PassThru
  - ps: ./build.ps1
#
#artifacts:
  - name: ZipMeUp
    path: 'bin/*.*'
#  - name: Config
#    path: 'bin/*.hcl'
